/*
L3 GROUPE B - PROJET DON DE SANG GROUPE 3 -
*/
/*
Numéro de carte étudiant : 22020352
Nom : DJUNAEDI
Prénom : Rendra
*/
/*
Numéro de carte étudiant : 22010095 
Nom : FAURA BEHAGUE
Prénom : MATTEO
*/

/*
CREATION DES TABLES
*/

prompt "Création des relations"

CREATE TABLE PERSONNE (
    NUM_PERSO VARCHAR(10),
    NOM VARCHAR(15) CONSTRAINT NOMPERSO NOT NULL,
    PRENOM VARCHAR(20),
    CONTACT NUMERIC(10,10),
    AGE NUMERIC(3,0),
    CONSTRAINT PK_NUM_PERSO PRIMARY KEY (NUM_PERSO)
);

CREATE TABLE DONNEUR (
    NUM_DONNEUR VARCHAR(10),
    EMAIL VARCHAR(30) CONSTRAINT EMAIL_CONSTRAINT_NOT_NULL NOT NULL,
    CONSTRAINT PK_NUM_DONNEUR PRIMARY KEY (NUM_DONNEUR),
    FOREIGN KEY (NUM_DONNEUR) REFERENCES PERSONNE(NUM_PERSO) ON DELETE CASCADE
);

CREATE TABLE PATIENT (
    NUM_PATIENT VARCHAR(10),
    GROUPE_SANG VARCHAR(3) CHECK (GROUPE_SANG IN ('O-','O+','A-','A+','B-','B+','AB-','AB+')),
    CONSTRAINT PK_PATIENT PRIMARY KEY (NUM_PATIENT),
    FOREIGN KEY (NUM_PATIENT) REFERENCES PERSONNE(NUM_PERSO) ON DELETE CASCADE
);

CREATE TABLE PERSONNEL (
    NUM_PERSONNEL VARCHAR(10),
    FONCTION VARCHAR(20),
    D_ANCIENNETE DATE,
    CONSTRAINT PK_PERSONNEL PRIMARY KEY (NUM_PERSONNEL),
    FOREIGN KEY (NUM_PERSONNEL) REFERENCES PERSONNE(NUM_PERSO) ON DELETE CASCADE
);

CREATE TABLE HOPITAL (
    CODE_HOPITAL NUMERIC(10,0),
    NOM varchar(128),
    ADRESSE varchar(128),
    CONSTRAINT PK_CODE_HOPITAL PRIMARY KEY (CODE_HOPITAL)
);

CREATE TABLE COLLECTE (
    ID_COLLECTE NUMERIC(10,0),
    D_DEBUT DATE,
    D_FIN DATE,
    LOCALISATION VARCHAR(128),
    URGENCE VARCHAR(10) CHECK (URGENCE IN ('URGENT','NORMAL')),
    CONSTRAINT PK_ID_COLLECTE PRIMARY KEY (ID_COLLECTE)
);

CREATE TABLE DON (
    ID_DON VARCHAR(10),
    QUANTITE INT CHECK (QUANTITE BETWEEN 400 AND 500),
    NATURE_DON VARCHAR(15) CHECK (NATURE_DON IN ('URGENT','NORMAL')),
    D_DON DATE,
    NUM_D VARCHAR(10),
    ID_C NUMERIC(10,0),
    CONSTRAINT PK_ID_DON PRIMARY KEY (ID_DON),
    FOREIGN KEY (NUM_D) REFERENCES DONNEUR (NUM_DONNEUR) ON DELETE CASCADE,
    FOREIGN KEY (ID_C) REFERENCES COLLECTE (ID_COLLECTE) ON DELETE CASCADE
);

CREATE TABLE TRAITE (
    NUM_TRAITEUR VARCHAR(10),
    ID_D VARCHAR(10),
    CODE_H NUMERIC(10,0),
    D_TRAITEMENT DATE,
    VALIDITE VARCHAR(15) CHECK (VALIDITE IN ('VALIDE','NON_VALIDE')),
    TYPE_SANG VARCHAR(3) CHECK (TYPE_SANG IN ('O-','O+','A-','A+','B-','B+','AB-','AB+')),
    CONSTRAINT NUM_TRAITE PRIMARY KEY (NUM_TRAITEUR, ID_D, CODE_H),
    FOREIGN KEY (NUM_TRAITEUR) REFERENCES PERSONNEL (NUM_PERSONNEL) ON DELETE CASCADE,
    FOREIGN KEY (ID_D) REFERENCES DON (ID_DON) ON DELETE CASCADE,
    FOREIGN KEY (CODE_H) REFERENCES HOPITAL (CODE_HOPITAL) ON DELETE CASCADE
);

CREATE TABLE TRANSFUSE (
    ID_D VARCHAR(10),
    NUM_P VARCHAR(10),
    CODE_H NUMERIC(10,0),
    D_TRANSFUSION DATE,
    CONSTRAINT NUM_TRANSUSION PRIMARY KEY (ID_D, NUM_P, CODE_H),
    FOREIGN KEY (ID_D) REFERENCES DON (ID_DON) ON DELETE CASCADE,
    FOREIGN KEY (NUM_P) REFERENCES PATIENT (NUM_PATIENT) ON DELETE CASCADE,
    FOREIGN KEY (CODE_H) REFERENCES HOPITAL (CODE_HOPITAL) ON DELETE CASCADE
);

prompt "Remplissage des tables!"

START remplissage_Groupe3.sql;

prompt "Création des procedures et fonctions"

CREATE OR REPLACE PROCEDURE INSERT_INTO_DONNEUR
    ( NUMERO PERSONNE.NUM_PERSO%TYPE, 
      NOM PERSONNE.NOM%TYPE, 
      PRENOM PERSONNE.PRENOM%TYPE, 
      CONTACT PERSONNE%TYPE, 
      AGE PERSONNE%TYPE, 
      EMAIL DONNEUR.EMAIL%TYPE) IS
    BEGIN

      INSERT INTO PERSONNE(NUMERO, NOM, PRENOM, CONTACT, AGE);
      INSERT INTO DONNEUR(NUMERO, EMAIL);

    END;