prompt -------------------------------------------;
prompt --- Suppression des anciens tuples --------;
prompt -------------------------------------------;

DELETE FROM TRANSFUSE;
DELETE FROM TRAITE;
DELETE FROM DON;
DELETE FROM COLLECTE;
DELETE FROM HOPITAL;
DELETE FROM PATIENT;
DELETE FROM PERSONNEL;
DELETE FROM DONNEUR;
DELETE FROM PERSONNE;

/*
SUPPRESSION DES RELATIONS (NORMALEMENT AVEC BON ORDRE)
*/
prompt -------------------------------------------;
prompt ---    Suppression des relations   --------;
prompt -------------------------------------------;

prompt "Suppression des relations"
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TRANSFUSE CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TRAITE CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE DON CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE COLLECTE CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE HOPITAL CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE PATIENT CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE PERSONNEL CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE DONNEUR CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE PERSONNE CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

/*
*************************************************
*/